.PHONY: clean All

All:
	@echo "----------Building project:[ steedCliteP - Debug ]----------"
	@cd "steedCliteP" && "$(MAKE)" -f  "steedCliteP.mk"
clean:
	@echo "----------Cleaning project:[ steedCliteP - Debug ]----------"
	@cd "steedCliteP" && "$(MAKE)" -f  "steedCliteP.mk" clean
